// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PromoEvent struct {
	ID                int64
	OrgID             pgtype.UUID
	SourceID          int64
	StoreID           int64
	Sku               string
	Titulo            string
	Preco             pgtype.Numeric
	PrecoAnterior     pgtype.Numeric
	Moeda             string
	EstoqueDisponivel bool
	BadgePromo        bool
	Url               string
	DetectedAt        pgtype.Timestamptz
	DedupBucket       pgtype.Timestamptz
}

type Source struct {
	ID              int64
	OrgID           pgtype.UUID
	StoreID         int64
	Url             string
	Strategy        string
	IntervalSeconds int32
	Selectors       []byte
	Enabled         bool
	LastCollectedAt pgtype.Timestamptz
	LastSnapshot    []byte
	LastError       *string
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Store struct {
	ID        int64
	OrgID     pgtype.UUID
	Nome      string
	Host      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
