// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promo_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPromoEvent = `-- name: InsertPromoEvent :execrows
INSERT INTO promo_events (
    org_id,
    source_id,
    store_id,
    sku,
    titulo,
    preco,
    preco_anterior,
    moeda,
    estoque_disponivel,
    badge_promo,
    url,
    detected_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (org_id, source_id, preco, dedup_bucket) DO NOTHING
`

type InsertPromoEventParams struct {
	OrgID             pgtype.UUID
	SourceID          int64
	StoreID           int64
	Sku               string
	Titulo            string
	Preco             pgtype.Numeric
	PrecoAnterior     pgtype.Numeric
	Moeda             string
	EstoqueDisponivel bool
	BadgePromo        bool
	Url               string
	DetectedAt        pgtype.Timestamptz
}

func (q *Queries) InsertPromoEvent(ctx context.Context, arg InsertPromoEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPromoEvent,
		arg.OrgID,
		arg.SourceID,
		arg.StoreID,
		arg.Sku,
		arg.Titulo,
		arg.Preco,
		arg.PrecoAnterior,
		arg.Moeda,
		arg.EstoqueDisponivel,
		arg.BadgePromo,
		arg.Url,
		arg.DetectedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
