// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	InsertPromoEvent(ctx context.Context, arg InsertPromoEventParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
