// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetEligibleSources(ctx context.Context, arg GetEligibleSourcesParams) ([]Source, error)
	GetSourceByID(ctx context.Context, arg GetSourceByIDParams) (Source, error)
	MarkSourceError(ctx context.Context, arg MarkSourceErrorParams) error
	UpdateSourceAfterCollect(ctx context.Context, arg UpdateSourceAfterCollectParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
