// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEligibleSources = `-- name: GetEligibleSources :many
SELECT
    id,
    org_id,
    store_id,
    url,
    strategy,
    interval_seconds,
    selectors,
    enabled,
    last_collected_at,
    last_snapshot,
    last_error,
    version,
    created_at,
    updated_at
FROM sources
WHERE org_id = $1
  AND enabled = true
  AND (
        last_collected_at IS NULL
     OR now() >= last_collected_at + (interval_seconds || ' seconds')::interval
  )
ORDER BY last_collected_at NULLS FIRST, id
LIMIT $2
`

type GetEligibleSourcesParams struct {
	OrgID pgtype.UUID
	Limit int32
}

func (q *Queries) GetEligibleSources(ctx context.Context, arg GetEligibleSourcesParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, getEligibleSources, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.StoreID,
			&i.Url,
			&i.Strategy,
			&i.IntervalSeconds,
			&i.Selectors,
			&i.Enabled,
			&i.LastCollectedAt,
			&i.LastSnapshot,
			&i.LastError,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT
    id,
    org_id,
    store_id,
    url,
    strategy,
    interval_seconds,
    selectors,
    enabled,
    last_collected_at,
    last_snapshot,
    last_error,
    version,
    created_at,
    updated_at
FROM sources
WHERE id = $1 AND org_id = $2
`

type GetSourceByIDParams struct {
	ID    int64
	OrgID pgtype.UUID
}

func (q *Queries) GetSourceByID(ctx context.Context, arg GetSourceByIDParams) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, arg.ID, arg.OrgID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.Url,
		&i.Strategy,
		&i.IntervalSeconds,
		&i.Selectors,
		&i.Enabled,
		&i.LastCollectedAt,
		&i.LastSnapshot,
		&i.LastError,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSourceError = `-- name: MarkSourceError :exec
UPDATE sources
SET
    last_error        = $1,
    last_collected_at = now(),
    version           = version + 1,
    updated_at        = now()
WHERE id = $2 AND org_id = $3
`

type MarkSourceErrorParams struct {
	LastError *string
	ID        int64
	OrgID     pgtype.UUID
}

func (q *Queries) MarkSourceError(ctx context.Context, arg MarkSourceErrorParams) error {
	_, err := q.db.Exec(ctx, markSourceError, arg.LastError, arg.ID, arg.OrgID)
	return err
}

const updateSourceAfterCollect = `-- name: UpdateSourceAfterCollect :execrows
UPDATE sources
SET
    last_snapshot     = $1,
    last_collected_at = now(),
    last_error        = NULL,
    version           = version + 1,
    updated_at        = now()
WHERE id = $2
  AND org_id = $3
  AND version = $4
`

type UpdateSourceAfterCollectParams struct {
	LastSnapshot []byte
	ID           int64
	OrgID        pgtype.UUID
	Version      int32
}

func (q *Queries) UpdateSourceAfterCollect(ctx context.Context, arg UpdateSourceAfterCollectParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSourceAfterCollect,
		arg.LastSnapshot,
		arg.ID,
		arg.OrgID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
